title: compiledwrong
email: compiledwrong+blog@gmail.com
description: >
  Some thoughts and conference notes
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://compwron.github.io" # the base hostname & protocol for your site
twitter_username: compiledwrong
github_username: compwron
highlighter: rouge
markdown: kramdown
