# Site settings
title: compwron
email: a@b.com
description: >
  Some stuff
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://compwron.github.io" # the base hostname & protocol for your site
twitter_username:
github_username: compwron
highlighter: pygments
  # Build settings
markdown: kramdown
